version: '3.4'
services:
  app:
    container_name: wechat-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 80
    ports:
      - 3000:80
  server:
    container_name: socket-io-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3005
      HOST: 0.0.0.0
    ports:
      - 3005:3005